---
- hosts: all
  sudo: yes

  vars:
    docker_version: 1.3.3

  tasks:
    - name: add docker repository key
      apt_key: url=https://get.docker.io/gpg state=present

    - name: add docker repository
      apt_repository: >
        repo="deb http://get.docker.io/ubuntu docker main" state=present

    - name: install docker and other packages
      apt: pkg={{ item }} state=present
      with_items:
        - lxc-docker-{{ docker_version }}
        - linux-image-extra-virtual

    - name: add vagrant user to docker and adm groups
      user: name=vagrant groups=docker,adm append=yes

    - name: build docker image
      command: >
        docker build -t tumbler .
      args:
        chdir: /sandbox

    - shell: 'echo "Step 1: get into the vagrant box with: vagrant ssh"'
      register: step1

    - shell: 'echo "Step 2: run the server with: docker run --net=host tumbler"'
      register: step2

    - shell: 'echo "Step 3: open your browser at http://localhost:5000"'
      register: step3

    - shell: 'echo "Step 4: disco!"'
      register: step4

    - debug: var=step1.stdout
    - debug: var=step2.stdout
    - debug: var=step3.stdout
    - debug: var=step4.stdout
